import ThemeRegistry from "@/theme/themeRegistry";
import "./globals.css";
import Wrapper from "@/components/user/Wrapper";
import { ReduxProviders } from "@/redux/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProviders>
        <ThemeRegistry>
          <body>
            <Wrapper>{children}</Wrapper>
          </body>
        </ThemeRegistry>
      </ReduxProviders>
    </html>
  );
}
